# Generated by Django 3.2.4 on 2022-01-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Category',
            new_name='ProductCategory',
        ),
    ]
